[package]
name = "chess_tail"
version = "1.0.1"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
libchess = { git = "https://github.com/irrelevantpiadina/libchess" }
hide_console = "0.2.1"

[profile.release]
debug = true
